# Generated by Django 4.0.4 on 2022-05-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplereference',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
