# Generated by Django 4.0.4 on 2022-05-18 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_sample_updated_at_samplereference_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='voter',
            field=models.ManyToManyField(related_name='vote_sample', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_sample', to=settings.AUTH_USER_MODEL),
        ),
    ]
